connector.name=iceberg
iceberg.catalog.type=rest
iceberg.rest-catalog.uri=http://polaris:8181/api/catalog
iceberg.rest-catalog.warehouse=icelake
iceberg.rest-catalog.security=OAUTH2
iceberg.rest-catalog.oauth2.credential=polaris:polaris
iceberg.rest-catalog.oauth2.scope=PRINCIPAL_ROLE:ALL
fs.native-s3.enabled=true
s3.endpoint=http://garage:3900
s3.region=us-east-1
s3.path-style-access=true
s3.aws-access-key=GK1f5cbdb2ac0aebcbb74e18d5
s3.aws-secret-key=b5057d94ab27275064a278e2e358bbe751d3610c26f7d6499bc5f0ca76996b29